@WebApiDotNet9_HostAddress = http://localhost:5284

GET {{WebApiDotNet9_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApiDotNet9_HostAddress}}/api/v1/controller
Accept: application/json

###